[generators.lists]
furaffinity = [
  "antidev",
  "arcarc",
  "bastion",
  "cobaltsnow",
  "dreamkeepers",
  "edjit7",
  "falvie",
  "fatalfox",
  "fiddleafox",
  "fisk",
  "glowfox",
  "grayhoof",
  "harmarist",
  "hyenolf",
  "icywaterspupper",
  "iztli",
  "jasonafex",
  "jaydraws",
  "kabier",
  "mangoyena",
  "marblesoda",
  "miles-df",
  "nyinxdelune",
  "opticbuster",
  "popparotzi",
  "sethpup",
  "shardfox",
  "soulbriar",
  "tslof",
  "xenoforge",
  "zaush",
]
