[tools]
deno = "latest"
node = "latest"
tombi = "latest"

[deps.deno]
auto = true
run = "deno install"
depends = ["deno"]
sources = ["deno.json*", "deno.lock", "package.json"]
outputs = ["node_modules"]
